name: Manual Publish to Mozilla store

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Update build time
        run: ./scripts/update-build-time.ts

      - name: Zip extensions
        run: |
          bun run zip:firefox --mv2
        env:
          VITE_LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
          VITE_LAST_FM_SHARED_SECRET: ${{ secrets.LAST_FM_SHARED_SECRET }}

      - name: Submit to stores
        run: |
          bun wxt submit \
            --firefox-zip .output/*-firefox.zip \
            --firefox-sources-zip .output/*-sources.zip
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          FIREFOX_CHANNEL: ${{ vars.FIREFOX_CHANNEL }}
